
version: 2

models:
  - name: cd_fact_sales
    description: "Sales fact"
    columns:
      - name: CustomerKey
      - name: BillToCustomerKey
      - name: DeliveryMethodKey
      - name: OrderID
      - name: InvoiceID
      - name: InvoiceLineID
      - name: SalespersonPersonID
      - name: InvoiceDateKey
      - name: CustomerPurchaseOrderNumber
      - name: IsCreditNote
      - name: CreditNoteReason
      - name: StockItemKey
      - name: Quantity
      - name: UnitPrice
      - name: TaxRate
      - name: TaxAmount
      - name: LineProfit
      - name: ExtendedPrice
      - name: SalesAmount
      - name: ETL_Date


  - name: cd_dim_customer
    description: "Customer dimension"
    columns:
      - name: CustomerKey
        tests:
          - unique
          - not_null
      - name: CustomerName
      - name: CustomerCategoryName
      - name: BuyingGroupName
      - name: CityName
      - name: StateProvinceName
      - name: SalesTerritory
      - name: CountryName
      - name: Continent
      - name: Region
      - name: SubRegion
      - name: ETL_Date
      

  - name: cd_dim_date
    description: "Date dimension"
    columns:
      - name: DateKey
        tests:
          - unique
          - not_null
      - name: Date
      - name: Day
      - name: MonthName
      - name: MonthNumber
      - name: Year
      - name: ETL_Date


  - name: cd_dim_deliverymethods
    description: "Delivery Method dimension"
    columns:
      - name: DeliveryMethodKey
        tests:
          - unique
          - not_null
      - name: DeliveryMethodName
      - name: ETL_Date


  - name: cd_dim_salesperson
    description: "Sales Person dimension"
    columns:
      - name: SalesPersonKey
        tests:
          - unique
          - not_null
      - name: FullName
      - name: ETL_Date

