
version: 2

models:
  - name: cf_sales_invoicelines
    description: "sales invoice lines"
    columns:
      - name: id
      - name:  InvoiceLineID
        tests:
          - unique
          - not_null
      - name:  InvoiceID
      - name:  StockItemID
      - name:  Description
      - name:  PackageTypeID
      - name:  Quantity
      - name:  UnitPrice
      - name:  TaxRate
      - name:  TaxAmount
      - name:  LineProfit
      - name:  ExtendedPrice
      - name:  LastEditedBy
      - name:  LastEditedWhen

          

  - name: cf_sales_invoices
    description: "sales invoice"
    columns:
      - name: InvoiceID
        tests:
          - unique
          - not_null
      - name:  CustomerID
      - name:  BillToCustomerID
      - name:  OrderID
      - name:  DeliveryMethodID
      - name:  ContactPersonID
      - name:  AccountsPersonID
      - name:  SalespersonPersonID
      - name:  PackedByPersonID
      - name:  InvoiceDate
      - name:  CustomerPurchaseOrderNumber
      - name:  IsCreditNote
      - name:  CreditNoteReason
      - name:  Comments
      - name:  DeliveryInstructions
      - name:  InternalComments
      - name:  TotalDryItems
      - name:  TotalChillerItems
      - name:  DeliveryRun
      - name:  RunPosition
      - name:  ReturnedDeliveryData
      - name:  ConfirmedDeliveryTime
      - name:  ConfirmedReceivedBy
      - name:  LastEditedBy
      - name:  LastEditedWhen

  - name: cf_customers
    description: "Customers"
    columns:
      - name: CustomerID
        tests:
          - unique
          - not_null
      - name: CustomerName
      - name: BillToCustomerID
      - name: CustomerCategoryID
      - name: BuyingGroupID
      - name: PrimaryContactPersonID
      - name: AlternateContactPersonID
      - name: DeliveryMethodID
      - name: DeliveryCityID
      - name: PostalCityID
      - name: CreditLimit
      - name: AccountOpenedDate
      - name: StandardDiscountPercentage
      - name: IsStatementSent
      - name: IsOnCreditHold
      - name: PaymentDays
      - name: PhoneNumber
      - name: FaxNumber
      - name: DeliveryRun
      - name: RunPosition
      - name: WebsiteURL
      - name: DeliveryAddressLine1
      - name: DeliveryAddressLine2
      - name: DeliveryPostalCode
      - name: ostalAddressLine1
      - name: PostalAddressLine2
      - name: PostalPostalCode
      - name: LastEditedBy
      - name: ValidFrom
      - name: ValidTo
 

  - name: cf_customercategories
    description: "customer categories"
    columns:
      - name: CustomerCategoryID
        tests:
          - unique
          - not_null
      - name: CustomerCategoryName
      - name: LastEditedBy
      - name: ValidFrom
      - name: ValidTo
      - name: updated_at



