# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python


name: Build_TestProj_Post_Install_Main


on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . 
        python test_post_install.py samples/testproj 0 samples/testproj
    - name: Archive testproj artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: |
            samples/testproj/target/            

